Courses/Models/Programs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Courses.Models
{
    public class Programs
    {

        public int Id { get; set; }
        [Display(Name = "Course title")]
        public string CourseTitle { get; set; }
        [Display(Name = "Course content")]
        public string CourseContent { get; set; }
        [Display(Name = "Course date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode =true,DataFormatString ="{0:MM/dd/yyyy}")]
        public DateTime CourseDate { get; set; }
        [Display(Name = "Course duration")]
        public string CourseDuration { get; set; }
        [Display(Name = "Course image")]
        public string CourseImage { get; set; }
        public int FieldId { get; set; }
        public virtual Fields Field { get; set; }
    }
}

Courses/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Courses.Models;

namespace Courses.Controllers
{
    
    public class ProgramsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Programs
        public ActionResult Index()
        {
            var programs = db.Programs.Include(p => p.Field);
            return View(programs.ToList());
        }

        // GET: Programs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programs programs = db.Programs.Find(id);
            if (programs == null)
            {
                return HttpNotFound();
            }
            return View(programs);
        }

        // GET: Programs/Create
        public ActionResult Create()
        {
            ViewBag.FieldId = new SelectList(db.Fields, "Id", "FieldName");
            return View();
        }

        // POST: Programs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Programs programs, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                programs.CourseImage = upload.FileName;
                db.Programs.Add(programs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FieldId = new SelectList(db.Fields, "Id", "FieldName", programs.FieldId);
            return View(programs);
        }

        // GET: Programs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programs programs = db.Programs.Find(id);
            if (programs == null)
            {
                return HttpNotFound();
            }
            ViewBag.FieldId = new SelectList(db.Fields, "Id", "FieldName", programs.FieldId);
            return View(programs);
        }

        // POST: Programs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Programs programs, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    programs.CourseImage = upload.FileName;
                    db.Entry(programs).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("MyImage", "Please select an image for a course");
                }
            }
                ViewBag.FieldId = new SelectList(db.Fields, "Id", "FieldName", programs.FieldId);
            return View(programs);
        }

        // GET: Programs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programs programs = db.Programs.Find(id);
            if (programs == null)
            {
                return HttpNotFound();
            }
            return View(programs);
        }

        // POST: Programs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Programs programs = db.Programs.Find(id);
            db.Programs.Remove(programs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Courses/Views/Programs/Create.cshtml
@model Courses.Models.Programs

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseDuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseDuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.CourseImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FieldId, "FieldId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FieldId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FieldId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Courses list", "Index")
</div>

Courses/Views/Programs/Delete.cshtml
@model Courses.Models.Programs

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Field.FieldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field.FieldName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.CourseImage)"
                 class="thumbnail" style="height:48px; width:48px;" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Courses list", "Index")
        </div>
    }
</div>

Courses/Views/Programs/Details.cshtml
@model Courses.Models.Programs

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Field.FieldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field.FieldName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.CourseImage)"
                 class="thumbnail" style="height:48px; width:48px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to Courses list", "Index")
</p>

Courses/Views/Programs/Edit.cshtml
@model Courses.Models.Programs

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        <!--error if there is no image-->
        <div class="alert alert-danger" id="error-div" style="display:none">
            <span id="view-err"></span>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseDuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseDuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="MyImage" />
                @Html.ValidationMessageFor(model => model.CourseImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FieldId, "FieldId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FieldId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FieldId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="save" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Courses list", "Index")
</div>

@section scripts{
    <script>
        $(function () {
            $("#save").click(function () {
                console.log("Save button clicked");
                if ($("#MyImage").val() == "") {
                    $("#error-div").fadeIn();
                    $("#view-err").append("Please select an image for a course");
                    return false;
                }
            });
        });
    </script>}

Courses/Views/Programs/Index.cshtml
@model IEnumerable<Courses.Models.Programs>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-stripped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Field.FieldName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseDuration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseImage)
        </th>
        <th>
            Action
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Field.FieldName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseDuration)
            </td>
            <td>
                <img src="~/Uploads/@Html.DisplayFor(modelItem => item.CourseImage)"
                     class="thumbnail" style="height:48px; width:48px;" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>